defaults: &defaults
  #working_directory: ./circleci
  docker:
    - image: circleci/node:8

version: 2
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  build:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build
  test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn test --passWithNoTests
  lint:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: ls -alh .
      - run: ls -alh ./node_modules/*
      - run: ls -alh ./node_modules/eslint/*
      - run: ls -alh ./node_modules/eslint/bin/*
      - run: yarn lint
  chromatic:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: yarn chromatic
workflows:
  version: 2
  tests:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
      - chromatic:
          requires:
            - build
