defaults: &defaults
  working_directory: ~/urbarium-admin-react
  environment:
    SKIP_PREFLIGHT_CHECK: "true"
    CI: "true"
    TERM: xterm
  docker:
    - image: cypress/base:12.16.1
jobs:
  prepare:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          command: npm ci
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - urbarium-admin-react
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run lint
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm test
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run build
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - urbarium-admin-react/
  cypress:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: |
          retry() { while ! $@ ; do ((--TIMES))||exit;sleep 10;done; }
          cypress() { (npm run cypress -- --record --key $CYPRESS_KEY); }
          npm run serve &
          sleep 5
          TIMES=3 retry cypress
  deploy-preview:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run deploy -- --debug -c -t $ZEIT_TOKEN
  deploy-prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run deploy -- --prod --debug -c -t $ZEIT_TOKEN
  cypress-prod:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: |
          retry() { while ! $@ ; do ((--TIMES))||exit;sleep 10;done; }
          cypress() { (CYPRESS_BASE_URL="${PROD_HOST}" npm run cypress --  --record --key $CYPRESS_KEY); }
          sleep 30
          TIMES=2 retry cypress
workflows:
  version: 2
  tests:
    jobs:
      - prepare
      - lint:
          requires:
            - prepare
      - test:
          requires:
            - prepare
      - build:
          requires:
            - lint
            - test
      - cypress:
          requires:
            - build
      - deploy-preview:
          requires:
            - cypress
      - deploy-prod:
          requires:
            - cypress
          filters:
            branches:
              only: master
      - cypress-prod:
          requires:
            - deploy-prod
          filters:
            branches:
              only: master
orbs:
  snyk: snyk/snyk@0.0.10
version: 2.1
